import { Flashcard } from '../../flashcard'
export const AminoAcids: [Flashcard[]] = [[
    {frontContent: "Alanine \n ALA \n A", backContent: "assets/flashcard-assets/amino-acids/alanine.png", position: 0},
    {frontContent: "Arginine \n ARG \n R", backContent: "assets/flashcard-assets/amino-acids/arginine.png", position: 1},
    {frontContent: "Asparagine \n ASN \n N", backContent: "assets/flashcard-assets/amino-acids/asparagine.png", position: 2},
    {frontContent: "Aspartic Acid \n ASP \n D", backContent: "assets/flashcard-assets/amino-acids/aspartic_acid.png", position: 3},
    {frontContent: "Cysteine \n CYS \n C", backContent: "assets/flashcard-assets/amino-acids/cysteine.png", position: 4},
    {frontContent: "Glutamine \n GLN \n Q", backContent: "assets/flashcard-assets/amino-acids/glutamine.png", position: 5},
    {frontContent: "Glutamic Acid \n GLU \n E", backContent: "assets/flashcard-assets/amino-acids/glutamic_acid.png", position: 6},
    {frontContent: "Glycine \n GLY \n G", backContent: "assets/flashcard-assets/amino-acids/glycine.png", position: 7},
    {frontContent: "Histidine \n HIS \n H", backContent: "assets/flashcard-assets/amino-acids/histidine.png", position: 8},
    {frontContent: "Isoleucine \n ILE \n I", backContent: "assets/flashcard-assets/amino-acids/isoleucine.png", position: 9},
    {frontContent: "Leucine \n LEU \n L", backContent: "assets/flashcard-assets/amino-acids/leucine.png", position: 10},
    {frontContent: "Lysine \n LYS \n K", backContent: "assets/flashcard-assets/amino-acids/lysine.png", position: 11},
    {frontContent: "Methionine \n MET \n M", backContent: "assets/flashcard-assets/amino-acids/methionine.png", position: 12},
    {frontContent: "Phenylalanine \n PHE \n F", backContent: "assets/flashcard-assets/amino-acids/phenylalanine.png", position: 13},
    {frontContent: "Proline \n PRO \n P", backContent: "assets/flashcard-assets/amino-acids/proline.png", position: 14},
    {frontContent: "Serine \n SER \n S", backContent: "assets/flashcard-assets/amino-acids/serine.png", position: 15},
    {frontContent: "Threonine \n THR \n T", backContent: "assets/flashcard-assets/amino-acids/threonine.png", position: 16},
    {frontContent: "Tryptophan \n TRP \n W", backContent: "assets/flashcard-assets/amino-acids/tryptophan.png", position: 17},
    {frontContent: "Tyrosine \n TYR \n Y", backContent: "assets/flashcard-assets/amino-acids/tyrosine.png", position: 18},
    {frontContent: "Valine \n VAL \n V", backContent: "assets/flashcard-assets/amino-acids/valine.png", position: 19},
] , [  
    {frontContent: "Alanine \n ALA \n A", backContent: "assets/flashcard-assets/amino-acids/alanine.png", position: 0},
    {frontContent: "Arginine \n ARG \n R", backContent: "assets/flashcard-assets/amino-acids/arginine.png", position: 1},
    {frontContent: "Asparagine \n ASN \n N", backContent: "assets/flashcard-assets/amino-acids/asparagine.png", position: 2},
    {frontContent: "Aspartic Acid \n ASP \n D", backContent: "assets/flashcard-assets/amino-acids/aspartic_acid.png", position: 3},
    {frontContent: "Cysteine \n CYS \n C", backContent: "assets/flashcard-assets/amino-acids/cysteine.png", position: 4},
    {frontContent: "Glutamine \n GLN \n Q", backContent: "assets/flashcard-assets/amino-acids/glutamine.png", position: 5},
    {frontContent: "Glutamic Acid \n GLU \n E", backContent: "assets/flashcard-assets/amino-acids/glutamic_acid.png", position: 6},
    {frontContent: "Glycine \n GLY \n G", backContent: "assets/flashcard-assets/amino-acids/glycine.png", position: 7},
    {frontContent: "Histidine \n HIS \n H", backContent: "assets/flashcard-assets/amino-acids/histidine.png", position: 8},
    {frontContent: "Isoleucine \n ILE \n I", backContent: "assets/flashcard-assets/amino-acids/isoleucine.png", position: 9},
    {frontContent: "Leucine \n LEU \n L", backContent: "assets/flashcard-assets/amino-acids/leucine.png", position: 10},
    {frontContent: "Lysine \n LYS \n K", backContent: "assets/flashcard-assets/amino-acids/lysine.png", position: 11},
    {frontContent: "Methionine \n MET \n M", backContent: "assets/flashcard-assets/amino-acids/methionine.png", position: 12},
    {frontContent: "Phenylalanine \n PHE \n F", backContent: "assets/flashcard-assets/amino-acids/phenylalanine.png", position: 13},
    {frontContent: "Proline \n PRO \n P", backContent: "assets/flashcard-assets/amino-acids/proline.png", position: 14},
    {frontContent: "Serine \n SER \n S", backContent: "assets/flashcard-assets/amino-acids/serine.png", position: 15},
    {frontContent: "Threonine \n THR \n T", backContent: "assets/flashcard-assets/amino-acids/threonine.png", position: 16},
    {frontContent: "Tryptophan \n TRP \n W", backContent: "assets/flashcard-assets/amino-acids/tryptophan.png", position: 17},
    {frontContent: "Tyrosine \n TYR \n Y", backContent: "assets/flashcard-assets/amino-acids/tyrosine.png", position: 18},
    {frontContent: "Valine \n VAL \n V", backContent: "assets/flashcard-assets/amino-acids/Valine.png", position: 19},
] , [
    {frontContent: "Alanine \n ALA \n A", backContent: "assets/flashcard-assets/amino-acids/alanine.png", position: 0},
    {frontContent: "Arginine \n ARG \n R", backContent: "assets/flashcard-assets/amino-acids/arginine.png", position: 1},
    {frontContent: "Asparagine \n ASN \n N", backContent: "assets/flashcard-assets/amino-acids/asparagine.png", position: 2},
    {frontContent: "Aspartic Acid \n ASP \n D", backContent: "assets/flashcard-assets/amino-acids/aspartic_acid.png", position: 3},
    {frontContent: "Cysteine \n CYS \n C", backContent: "assets/flashcard-assets/amino-acids/cysteine.png", position: 4},
    {frontContent: "Glutamine \n GLN \n Q", backContent: "assets/flashcard-assets/amino-acids/glutamine.png", position: 5},
    {frontContent: "Glutamic Acid \n GLU \n E", backContent: "assets/flashcard-assets/amino-acids/glutamic_acid.png", position: 6},
    {frontContent: "Glycine \n GLY \n G", backContent: "assets/flashcard-assets/amino-acids/glycine.png", position: 7},
    {frontContent: "Histidine \n HIS \n H", backContent: "assets/flashcard-assets/amino-acids/histidine.png", position: 8},
    {frontContent: "Isoleucine \n ILE \n I", backContent: "assets/flashcard-assets/amino-acids/isoleucine.png", position: 9},
    {frontContent: "Leucine \n LEU \n L", backContent: "assets/flashcard-assets/amino-acids/leucine.png", position: 10},
    {frontContent: "Lysine \n LYS \n K", backContent: "assets/flashcard-assets/amino-acids/lysine.png", position: 11},
    {frontContent: "Methionine \n MET \n M", backContent: "assets/flashcard-assets/amino-acids/methionine.png", position: 12},
    {frontContent: "Phenylalanine \n PHE \n F", backContent: "assets/flashcard-assets/amino-acids/phenylalanine.png", position: 13},
    {frontContent: "Proline \n PRO \n P", backContent: "assets/flashcard-assets/amino-acids/proline.png", position: 14},
    {frontContent: "Serine \n SER \n S", backContent: "assets/flashcard-assets/amino-acids/serine.png", position: 15},
    {frontContent: "Threonine \n THR \n T", backContent: "assets/flashcard-assets/amino-acids/threonine.png", position: 16},
    {frontContent: "Tryptophan \n TRP \n W", backContent: "assets/flashcard-assets/amino-acids/tryptophan.png", position: 17},
    {frontContent: "Tyrosine \n TYR \n Y", backContent: "assets/flashcard-assets/amino-acids/tyrosine.png", position: 18},
    {frontContent: "Valine \n VAL \n V", backContent: "assets/flashcard-assets/amino-acids/Valine.png", position: 19},
]]

