import { Flashcard } from '../../flashcard'
export const AminoAcids: [Flashcard[]] = [[
    {frontContent: "Alanine \n ALA \n A", backContent: "assets/flashcard-assets/amino-acids/alanine.png", position: 0, frontContentType: "text", backContentType: "image"},
    {frontContent: "Arginine \n ARG \n R", backContent: "assets/flashcard-assets/amino-acids/arginine.png", position: 1, frontContentType: "text", backContentType: "image"},
    {frontContent: "Asparagine \n ASN \n N", backContent: "assets/flashcard-assets/amino-acids/asparagine.png", position: 2, frontContentType: "text", backContentType: "image"},
    {frontContent: "Aspartic Acid \n ASP \n D", backContent: "assets/flashcard-assets/amino-acids/aspartic_acid.png", position: 3, frontContentType: "text", backContentType: "image"},
    {frontContent: "Cysteine \n CYS \n C", backContent: "assets/flashcard-assets/amino-acids/cysteine.png", position: 4, frontContentType: "text", backContentType: "image"},
    {frontContent: "Glutamine \n GLN \n Q", backContent: "assets/flashcard-assets/amino-acids/glutamine.png", position: 5, frontContentType: "text", backContentType: "image"},
    {frontContent: "Glutamic Acid \n GLU \n E", backContent: "assets/flashcard-assets/amino-acids/glutamic_acid.png", position: 6, frontContentType: "text", backContentType: "image"},
    {frontContent: "Glycine \n GLY \n G", backContent: "assets/flashcard-assets/amino-acids/glycine.png", position: 7, frontContentType: "text", backContentType: "image"},
    {frontContent: "Histidine \n HIS \n H", backContent: "assets/flashcard-assets/amino-acids/histidine.png", position: 8, frontContentType: "text", backContentType: "image"},
    {frontContent: "Isoleucine \n ILE \n I", backContent: "assets/flashcard-assets/amino-acids/isoleucine.png", position: 9, frontContentType: "text", backContentType: "image"},
    {frontContent: "Leucine \n LEU \n L", backContent: "assets/flashcard-assets/amino-acids/leucine.png", position: 10, frontContentType: "text", backContentType: "image"},
    {frontContent: "Lysine \n LYS \n K", backContent: "assets/flashcard-assets/amino-acids/lysine.png", position: 11, frontContentType: "text", backContentType: "image"},
    {frontContent: "Methionine \n MET \n M", backContent: "assets/flashcard-assets/amino-acids/methionine.png", position: 12, frontContentType: "text", backContentType: "image"},
    {frontContent: "Phenylalanine \n PHE \n F", backContent: "assets/flashcard-assets/amino-acids/phenylalanine.png", position: 13, frontContentType: "text", backContentType: "image"},
    {frontContent: "Proline \n PRO \n P", backContent: "assets/flashcard-assets/amino-acids/proline.png", position: 14, frontContentType: "text", backContentType: "image"},
    {frontContent: "Serine \n SER \n S", backContent: "assets/flashcard-assets/amino-acids/serine.png", position: 15, frontContentType: "text", backContentType: "image"},
    {frontContent: "Threonine \n THR \n T", backContent: "assets/flashcard-assets/amino-acids/threonine.png", position: 16, frontContentType: "text", backContentType: "image"},
    {frontContent: "Tryptophan \n TRP \n W", backContent: "assets/flashcard-assets/amino-acids/tryptophan.png", position: 17, frontContentType: "text", backContentType: "image"},
    {frontContent: "Tyrosine \n TYR \n Y", backContent: "assets/flashcard-assets/amino-acids/tyrosine.png", position: 18, frontContentType: "text", backContentType: "image"},
    {frontContent: "Valine \n VAL \n V", backContent: "assets/flashcard-assets/amino-acids/valine.png", position: 19, frontContentType: "text", backContentType: "image"},
] , [  
    {frontContent: "ALA", backContent: "Alanine \n A", position: 0, frontContentType: "text", backContentType: "text"},
    {frontContent: "ARG", backContent: "Arginine \n R", position: 1, frontContentType: "text", backContentType: "text"},
    {frontContent: "ASN", backContent: "Asparagine \n N", position: 2, frontContentType: "text", backContentType: "text"},
    {frontContent: "ASP", backContent: "Aspartic Acid \n D", position: 3, frontContentType: "text", backContentType: "text"},
    {frontContent: "CYS", backContent: "Cysteine \n C", position: 4, frontContentType: "text", backContentType: "text"},
    {frontContent: "GLN", backContent: "Glutamine \n Q", position: 5, frontContentType: "text", backContentType: "text"},
    {frontContent: "GLU", backContent: "Glutamic Acid \n E", position: 6, frontContentType: "text", backContentType: "text"},
    {frontContent: "GLY", backContent: "Glycine \n G", position: 7, frontContentType: "text", backContentType: "text"},
    {frontContent: "HIS", backContent: "Histidine \n H", position: 8, frontContentType: "text", backContentType: "text"},
    {frontContent: "ILE", backContent: "Isoleucine \n I", position: 9, frontContentType: "text", backContentType: "text"},
    {frontContent: "LEU", backContent: "Leucine \n L", position: 10, frontContentType: "text", backContentType: "text"},
    {frontContent: "LYS", backContent: "Lysine \n K", position: 11, frontContentType: "text", backContentType: "text"},
    {frontContent: "MET", backContent: "Methionine \n M", position: 12, frontContentType: "text", backContentType: "text"},
    {frontContent: "PHE", backContent: "Phenylalanine \n F", position: 13, frontContentType: "text", backContentType: "text"},
    {frontContent: "PRO", backContent: "Proline \n P", position: 14, frontContentType: "text", backContentType: "text"},
    {frontContent: "SER", backContent: "Serine \n S", position: 15, frontContentType: "text", backContentType: "text"},
    {frontContent: "THR", backContent: "Threonine \n T", position: 16, frontContentType: "text", backContentType: "text"},
    {frontContent: "TRP", backContent: "Tryptophan \n W", position: 17, frontContentType: "text", backContentType: "text"},
    {frontContent: "TYR", backContent: "Tyrosine \n Y", position: 18, frontContentType: "text", backContentType: "text"},
    {frontContent: "VAL", backContent: "Valine \n V", position: 19, frontContentType: "text", backContentType: "text"},
] , [
    {frontContent: "A", backContent: "Alanine \n ALA", position: 0, frontContentType: "text", backContentType: "text"},
    {frontContent: "R", backContent: "Arginine \n ARG", position: 1, frontContentType: "text", backContentType: "text"},
    {frontContent: "N", backContent: "Asparagine \n ASN", position: 2, frontContentType: "text", backContentType: "text"},
    {frontContent: "D", backContent: "Aspartic \n ASP", position: 3, frontContentType: "text", backContentType: "text"},
    {frontContent: "C", backContent: "Cysteine \n CYS", position: 4, frontContentType: "text", backContentType: "text"},
    {frontContent: "Q", backContent: "Glutamine \n GLN", position: 5, frontContentType: "text", backContentType: "text"},
    {frontContent: "E", backContent: "Glutamic \n GLU", position: 6, frontContentType: "text", backContentType: "text"},
    {frontContent: "G", backContent: "Glycine \n GLY", position: 7, frontContentType: "text", backContentType: "text"},
    {frontContent: "H", backContent: "Histidine \n HIS", position: 8, frontContentType: "text", backContentType: "text"},
    {frontContent: "I", backContent: "Isoleucine \n ILE", position: 9, frontContentType: "text", backContentType: "text"},
    {frontContent: "L", backContent: "Leucine \n LEU", position: 10, frontContentType: "text", backContentType: "text"},
    {frontContent: "K", backContent: "Lysine \n LYS", position: 11, frontContentType: "text", backContentType: "text"},
    {frontContent: "M", backContent: "Methionine \n MET", position: 12, frontContentType: "text", backContentType: "text"},
    {frontContent: "F", backContent: "Phenylalanine \n PHE", position: 13, frontContentType: "text", backContentType: "text"},
    {frontContent: "P", backContent: "Proline \n PRO", position: 14, frontContentType: "text", backContentType: "text"},
    {frontContent: "S", backContent: "Serine \n SER", position: 15, frontContentType: "text", backContentType: "text"},
    {frontContent: "T", backContent: "Threonine \n THR", position: 16, frontContentType: "text", backContentType: "text"},
    {frontContent: "W", backContent: "Tryptophan \n TRP", position: 17, frontContentType: "text", backContentType: "text"},
    {frontContent: "Y", backContent: "Tyrosine \n TYR", position: 18, frontContentType: "text", backContentType: "text"},
    {frontContent: "V", backContent: "Valine \n VAL", position: 19, frontContentType: "text", backContentType: "text"},
]]

