export const AminoAcids: object[] = [
    {front: ["Alanine", "ALA", "A"], back: "assets/flashcard-assets/amino-acids/alanine.png"},
    {front: ["Arginine", "ARG", "R"], back: "assets/flashcard-assets/amino-acids/arginine.png"},
    {front: ["Asparagine", "ASN", "N"], back: "assets/flashcard-assets/amino-acids/asparagine.png"},
    {front: ["Aspartic Acid", "ASP", "D"], back: "assets/flashcard-assets/amino-acids/aspartic_acid.png"},
    {front: ["Cysteine", "CYS", "C"], back: "assets/flashcard-assets/amino-acids/cysteine.png"},
    {front: ["Glutamine", "GLN", "Q"], back: "assets/flashcard-assets/amino-acids/glutamine.png"},
    {front: ["Glutamic Acid", "GLU", "E"], back: "assets/flashcard-assets/amino-acids/glutamic_acid.png"},
    {front: ["Glycine", "GLY", "G"], back: "assets/flashcard-assets/amino-acids/glycine.png"},
    {front: ["Histidine", "HIS", "H"], back: "assets/flashcard-assets/amino-acids/histidine.png"},
    {front: ["Isoleucine", "ILE", "I"], back: "assets/flashcard-assets/amino-acids/isoleucine.png"},
    {front: ["Leucine", "LEU", "L"], back: "assets/flashcard-assets/amino-acids/leucine.png"},
    {front: ["Lysine", "LYS", "K"], back: "assets/flashcard-assets/amino-acids/lysine.png"},
    {front: ["Methionine", "MET", "M"], back: "assets/flashcard-assets/amino-acids/methionine.png"},
    {front: ["Phenylalanine", "PHE", "F"], back: "assets/flashcard-assets/amino-acids/phenylalanine.png"},
    {front: ["Proline", "PRO", "P"], back: "assets/flashcard-assets/amino-acids/proline.png"},
    {front: ["Serine", "SER", "S"], back: "assets/flashcard-assets/amino-acids/serine.png"},
    {front: ["Threonine", "THR", "T"], back: "assets/flashcard-assets/amino-acids/threonine.png"},
    {front: ["Tryptophan", "TRP", "W"], back: "assets/flashcard-assets/amino-acids/tryptophan.png"},
    {front: ["Tyrosine", "TYR", "Y"], back: "assets/flashcard-assets/amino-acids/tyrosine.png"},
    {front: ["Valine", "VAL", "V"], back: "assets/flashcard-assets/amino-acids/Valine.png"},
]
